### PR TITLE
WMS config from URL

### PR DESCRIPTION
**Pull request by roarmstrong**
Update docker command to be a script which will download a new WMS config file from a URL if required.

### CODE REVIEW

**Comment by alexgleith** [comment]
Looks good.

I think it would be better if it was part of the [entrypoint](https://github.com/opendatacube/datacube-core/blob/develop/docker/docker-entrypoint.sh) file, as that wont be overwritten by another run command... plus, folks might like to change the run command to have more processes or threads or some other gunicorn flags. It does mean duplicating the core entrypoint file, though, so it's a bit of a compromise either way!

**Comment by roarmstrong** [comment]
Good point! How about a `wms-entrypoint.sh` which runs the config script and then passes all arguments to the `docker-entrypoint.sh` ?

**Comment by alexgleith** [comment]
Great idea! Does it work?

Also, I'm not sure how WGET handles a 404 error, but we should try to ensure that it doesn't write a file full of HTML if it fails to get the config, so that it falls back to the other config file.

Just tested, and wget will write an empty file on a fail. We should probably do something like this:

`A=$$; ( wget -q "http://foo.com/pipo.txt" -O $A.d && mv $A.d pipo.txt ) || (rm $A.d; echo "Removing temp file")` (from: https://stackoverflow.com/questions/89989/is-there-a-curl-wget-option-that-says-not-to-save-files-upon-http-errors)

**Comment by roarmstrong** [comment]
Seems to pass everything through to the datacube entrypoint fine! I'll implement the wget fixes next.

**Pull request merged**
